const recipes = [
{
id:1,
name:"Veg Fried Rice",
ingredients:["rice","carrot","peas","soy sauce"],
diet:"vegetarian",
difficulty:"Easy",
time:20,
servings:2,
calories:350,
protein:8,
steps:["Cook rice","Saute vegetables","Mix together","Serve hot"]
},
{
id:2,
name:"Grilled Chicken",
ingredients:["chicken","salt","pepper"],
diet:"non-veg",
difficulty:"Medium",
time:30,
servings:2,
calories:450,
protein:40,
steps:["Season chicken","Grill 20 mins","Serve"]
},
{
id:3,
name:"Vegan Salad",
ingredients:["lettuce","tomato","cucumber"],
diet:"vegan",
difficulty:"Easy",
time:10,
servings:1,
calories:150,
protein:3,
steps:["Chop vegetables","Mix","Serve fresh"]
},
{
id:4,
name:"Pasta Alfredo",
ingredients:["pasta","milk","cheese"],
diet:"vegetarian",
difficulty:"Medium",
time:25,
servings:2,
calories:500,
protein:15,
steps:["Boil pasta","Prepare sauce","Combine"]
},
{
id:5,
name:"Omelette",
ingredients:["egg","salt","onion"],
diet:"vegetarian",
difficulty:"Easy",
time:10,
servings:1,
calories:200,
protein:12,
steps:["Beat eggs","Cook in pan","Serve"]
},
{
id:6,
name:"Chicken Curry",
ingredients:["chicken","onion","tomato","spices"],
diet:"non-veg",
difficulty:"Medium",
time:40,
servings:3,
calories:600,
protein:45,
steps:["Saute onion","Add chicken","Add spices","Cook 30 mins"]
},
{
id:7,
name:"Dal Tadka",
ingredients:["lentils","onion","tomato","spices"],
diet:"vegan",
difficulty:"Easy",
time:30,
servings:3,
calories:300,
protein:18,
steps:["Boil lentils","Prepare tadka","Mix"]
},
{
id:8,
name:"Paneer Butter Masala",
ingredients:["paneer","butter","tomato","cream"],
diet:"vegetarian",
difficulty:"Medium",
time:35,
servings:3,
calories:550,
protein:22,
steps:["Cook gravy","Add paneer","Simmer"]
},
{
id:9,
name:"Chicken Sandwich",
ingredients:["bread","chicken","mayonnaise"],
diet:"non-veg",
difficulty:"Easy",
time:15,
servings:1,
calories:400,
protein:25,
steps:["Toast bread","Add filling","Serve"]
},
{
id:10,
name:"Fruit Smoothie",
ingredients:["banana","milk","berries"],
diet:"vegetarian",
difficulty:"Easy",
time:5,
servings:1,
calories:180,
protein:6,
steps:["Blend all","Serve chilled"]
},
{
id:11,
name:"Tofu Stir Fry",
ingredients:["tofu","soy sauce","vegetables"],
diet:"vegan",
difficulty:"Medium",
time:20,
servings:2,
calories:320,
protein:18,
steps:["Saute tofu","Add vegetables","Add sauce"]
},
{
id:12,
name:"Egg Fried Rice",
ingredients:["rice","egg","soy sauce"],
diet:"vegetarian",
difficulty:"Easy",
time:20,
servings:2,
calories:380,
protein:14,
steps:["Cook rice","Add egg","Mix"]
},
{
id:13,
name:"Beef Steak",
ingredients:["beef","salt","pepper"],
diet:"non-veg",
difficulty:"Hard",
time:45,
servings:2,
calories:700,
protein:60,
steps:["Season beef","Grill","Rest and serve"]
},
{
id:14,
name:"Vegetable Soup",
ingredients:["carrot","beans","water","salt"],
diet:"vegan",
difficulty:"Easy",
time:25,
servings:3,
calories:120,
protein:4,
steps:["Boil vegetables","Season","Serve"]
},
{
id:15,
name:"Chicken Biryani",
ingredients:["rice","chicken","spices"],
diet:"non-veg",
difficulty:"Hard",
time:60,
servings:4,
calories:800,
protein:50,
steps:["Cook chicken","Layer rice","Dum cooking"]
},
{
id:16,
name:"Avocado Toast",
ingredients:["bread","avocado"],
diet:"vegan",
difficulty:"Easy",
time:10,
servings:1,
calories:220,
protein:5,
steps:["Toast bread","Spread avocado"]
},
{
id:17,
name:"Chole",
ingredients:["chickpeas","onion","tomato","spices"],
diet:"vegan",
difficulty:"Medium",
time:40,
servings:3,
calories:350,
protein:16,
steps:["Boil chickpeas","Prepare gravy","Cook together"]
},
{
id:18,
name:"Fish Fry",
ingredients:["fish","salt","spices"],
diet:"non-veg",
difficulty:"Medium",
time:25,
servings:2,
calories:500,
protein:45,
steps:["Marinate fish","Fry"]
},
{
id:19,
name:"Cheese Pizza",
ingredients:["flour","cheese","tomato"],
diet:"vegetarian",
difficulty:"Hard",
time:50,
servings:3,
calories:900,
protein:30,
steps:["Prepare dough","Add toppings","Bake"]
},
{
id:20,
name:"Protein Shake",
ingredients:["milk","protein powder","banana"],
diet:"vegetarian",
difficulty:"Easy",
time:5,
servings:1,
calories:250,
protein:30,
steps:["Blend ingredients"]
}
];
